version: "3.7"

services:
  trust-anchor:
    image: obada/trust-anchor:develop
    container_name: ta
    restart: always
    environment:
      - TA_URL=http://trust-anchor
      - AUTH_PUBLIC_KEY=/home/ta/.ssh/ta_api.pub.pem
      - AUTH_PRIVATE_KEY=/home/ta/.ssh/ta_api.pem
    volumes:
      - ./ta/keys:/home/ta/.ssh
    networks:
      - applications

  explorer:
    image: obada/explorer:playground
    container_name: explorer
    restart: always
    ports:
      - 3000:3000
    networks:
      - applications
      
  rdgo:
    image: obada/rdgo:develop
    container_name: rdgo
    restart: always
    environment:
      - RPC_HOST=http://localhost
      - TA_TOKEN=sfsf
      - TA_URL=http://trust-anchor
      - IPFS_HOST=http://ipfs:5001
    ports:
      - "8585:8585"
    networks:
      - applications

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    restart: always
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/data:/data/ipfs
    ports:
      - "4002:4001"
      - "4003:4001/udp" 
      - "8084:8080"
      - "5002:5001"
    networks:
      - applications

  node:
    image: obada/cored:develop
    container_name: node
    restart: always
    volumes:
      - ./nodes/node/cored:/home/obada/.cored:Z
    command: cored start --home /home/obada/.cored
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    networks:
      - obadanet
      - applications

  testnet-init:
    image: obada/cored:develop
    container_name: testnet-init
    environment:
      CHAINID: "obada-playgroud"
    volumes:
      - ./testnet-init.sh:/home/obada/testnet-init.sh
      - ./nodes:/home/obada/nodes
    command: "./testnet-init.sh"
      
  tradeloop-node:
    image: obada/cored:develop
    container_name: tradeloop-node
    environment:
      - ID=0
    volumes:
      - ./nodes/node0/cored:/home/obada/.cored:Z
    command: cored start --home /home/obada/.cored
    networks:
      obadanet:
        ipv4_address: 172.22.0.2
      
  obs-node:
    image: obada/cored:develop
    container_name: obs-node
    environment:
      - ID=1
    volumes:
      - ./nodes/node1/cored:/home/obada/.cored:Z
    command: cored start --home /home/obada/.cored
    networks:
      obadanet:
        ipv4_address: 172.22.0.3

  usody-node:
    image: obada/cored:develop
    container_name: usody-node
    environment:
      - ID=2
    volumes:
      - ./nodes/node2/cored:/home/obada/.cored:Z
    command: cored start --home /home/obada/.cored
    networks:
      obadanet:
        ipv4_address: 172.22.0.4

  ascidi-node:
    image: obada/cored:develop
    container_name: ascidi-node
    environment:
      - ID=3
    volumes:
      - ./nodes/node3/cored:/home/obada/.cored:Z
    command: cored start --home /home/obada/.cored
    networks:
      obadanet:
        ipv4_address: 172.22.0.5
      
networks:
  obadanet:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
  applications:
    name: applications
