version: "3.7"

services:
  trust-anchor:
    image: obada/trust-anchor:develop
    container_name: ta
    restart: always
    environment:
      - TA_URL=http://trust-anchor
      - AUTH_PUBLIC_KEY=/home/ta/.ssh/ta_api.pub.pem
      - AUTH_PRIVATE_KEY=/home/ta/.ssh/ta_api.pem
    volumes:
      - ./ta/keys:/home/ta/.ssh
    networks:
      - applications
      
  rdgo:
    image: obada/rdgo:develop
    container_name: rdgo
    restart: always
    environment:
      - RPC_HOST=http://localhost
      - TA_TOKEN=sfsf
      - TA_URL=http://trust-anchor
      - IPFS_HOST=http://ipfs:5001
    ports:
      - "8585:8585"
    networks:
      - applications

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    restart: always
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/data:/data/ipfs
    ports:
      - "4002:4001"
      - "4003:4001/udp" 
      - "8084:8080"
      - "5002:5001"
    networks:
      - applications

  node:
    image: obada/cored
    container_name: node
    restart: always
    volumes:
      - ./nodes/node/cored:/home/cored/.core:Z
    command: cored start
    ports:
     - "26657:26657"
     - "8545:8545"
     - "8546:8546"
     - "8125:8125"
    networks:
      - obadanet
      - applications

  testnet-init:
    image: obada/cored
    container_name: testnet-init
    environment:
      DAEMON_HOME: "/home/cored/nodes/"
    volumes:
      - ./testnet-init.sh:/home/cored/testnet-init.sh
      - ./nodes:/home/cored/nodes
    command: "./testnet-init.sh"
      
  obs-node:
    image: obada/cored
    container_name: obs-node
    restart: always
    environment:
      - ID=obs
    volumes:
      - ./nodes/obs-node/cored:/home/cored/.core:Z
    command: cored start
    networks:
      - obadanet
      
networks:
  obadanet:
  applications:
    name: applications
  
    
