version: "3.7"

services:
  trust-anchor:
    image: obada/trust-anchor:develop
    container_name: ta
    restart: always
    networks:
      - applications
      
  rdgo:
    image: obada/rdgo:develop
    container_name: rdgo
    restart: always
    environment:
      - RPC_HOST=http://localhost
      - TA_TOKEN=sfsf
      - TA_URL=http://trust-anchor
      - IPFS_HOST=http://ipfs:5001
    ports:
      - "8585:8585"
    networks:
      - applications

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    restart: always
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/data:/data/ipfs
    ports:
      - "4002:4001"
      - "4003:4001/udp" 
      - "8084:8080"
      - "5002:5001"
    networks:
      - applications

  node:
    image: obada/fullcore:develop
    container_name: node
    restart: always
    volumes:
      - ./nodes/node/fullcored:/home/obada/.fullcored:Z
    command: ethermintd start --keyring-backend test
    ports:
     - "26657:26657"
     - "8545:8545"
     - "8546:8546"
     - "8125:8125"
    networks:
      - obadanet
      - applications

  testnet-init:
    image: obada/fullcore:develop
    container_name: testnet-init
    volumes:
      - ./testnet-init.sh:/home/obada/testnet-init.sh
      - ./nodes:/home/obada/nodes
    command: "./testnet-init.sh"
    
  tradeloop-node:
    image: obada/fullcore:develop
    container_name: tradeloop-node
    environment:
      - ID=0
    volumes:
      - ./nodes/node0/fullcored:/home/obada/.fullcored:Z
    command: ethermintd start --keyring-backend test
    networks:
      - obadanet
      
  obs-node:
    image: obada/fullcore:develop
    container_name: obs-node
    environment:
      - ID=1
    volumes:
      - ./nodes/node1/fullcored:/home/obada/.fullcored:Z
    command: ethermintd start --trace --keyring-backend test
    networks:
      - obadanet

  usody-node:
    image: obada/fullcore:develop
    container_name: usody-node
    environment:
      - ID=2
    volumes:
      - ./nodes/node2/fullcored:/home/obada/.fullcored:Z
    command: ethermintd start --trace --keyring-backend test
    networks:
      - obadanet

  ascidi-node:
    image: obada/fullcore:develop
    container_name: ascidi-node
    environment:
      - ID=3
    volumes:
      - ./nodes/node3/fullcored:/home/obada/.fullcored:Z
    command: ethermintd start --trace --keyring-backend test
    networks:
      - obadanet
      
networks:
  obadanet:
  applications:
    name: applications
  
    
