version: "3.7"

services:
  hasura:
    image: hasura/graphql-engine:v2.1.1
    container_name: hasura
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./hasura:/home/hasura/metadata
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://bdjuno:supersecure@bdjuno_db:5432/bdjuno_db
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://bdjuno:supersecure@bdjuno_db:5432/bdjuno_db
      HASURA_GRAPHQL_DATABASE_URL: postgres://bdjuno:supersecure@bdjuno_db:5432/bdjuno_db
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    depends_on:
      - bdjuno_db
    networks:
      - bdjuno
      - public

  bdjuno-genesis:
    image: obada/bdjuno
    container_name: bdjuno-genesis
    volumes:
      - ./bdjuno:/root/.bdjuno
      - ./nodes/node:/root/node
    command: bdjuno parse-genesis
    networks:
      - bdjuno

  bdjuno:
    image: obada/bdjuno
    container_name: bdjuno
    restart: always
    volumes:
      - ./bdjuno:/root/.bdjuno
    command: bdjuno parse
    depends_on:
      - bdjuno_db
    networks:
      - bdjuno

  bdjuno_db:
    image: postgres
    container_name: bdjuno_db
    restart: always
    environment:
      - POSTGRES_USER=bdjuno
      - POSTGRES_DB=bdjuno_db
      - POSTGRES_PASSWORD=supersecure
    volumes:
      - ./bdjuno/data:/var/lib/postgresql/data
      - ./bdjuno/schema:/root/schema
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - bdjuno

  explorer:
    image: obada/explorer:playground
    container_name: explorer
    restart: always
    ports:
      - 3000:3000
    networks:
      - public

  rd:
    image: obada/fullcore-ui:develop
    container_name: rd
    restart: always
    ports:
      - "8090:80"
    networks:
      - public

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    restart: always
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/data:/data/ipfs
    ports:
      - "4002:4001"
      - "4003:4001/udp" 
      - "8084:8080"
      - "5001:5001"
    networks:
      - public

  faucet:
    image: obada/fullcore:develop
    container_name: faucet
    restart: always
    volumes:
      - ./nodes/faucet:/home/obada/.fullcore:Z
    command: fullcored start
    networks:
      - faucet
      - public

  node:
    image: obada/fullcore:develop
    container_name: node
    restart: always
    volumes:
      - ./nodes/node:/home/obada/.fullcore:Z
    command: fullcored start
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    networks:
      - public

  val-node1:
    image: obada/fullcore:develop
    container_name: val-node1
    restart: always
    volumes:
      - ./nodes/val-node1:/home/obada/.fullcore:Z
    command: fullcored start --trace
    networks:
      - node1

  sentry-node1:
    image: obada/fullcore:develop
    container_name: sentry-node1
    restart: always
    volumes:
      - ./nodes/sentry-node1:/home/obada/.fullcore:Z
    command: fullcored start --trace
    networks:
      - node1
      - public
      
  val-node2:
    image: obada/fullcore:develop
    container_name: val-node2
    restart: always
    volumes:
      - ./nodes/val-node2:/home/obada/.fullcore:Z
    command: fullcored start --trace
    networks:
      - node2

  sentry-node2:
    image: obada/fullcore:develop
    container_name: sentry-node2
    restart: always
    volumes:
      - ./nodes/sentry-node2:/home/obada/.fullcore:Z
    command: fullcored start --trace
    networks:
      - node2
      - public
      
networks:
  public:
  node1:
  node2:
  faucet:
  bdjuno:
    name: bdjuno
