chain:
    bech32_prefix: obada
    modules: []
node:
    type: remote
    config:
      rpc:
        client_name: juno
        address: http://node:26657
        max_connections: 20
      grpc:
        address: http://node:9090
        insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    genesis_file_path: /root/node/cored/config/genesis.json
database:
    name: bdjuno_db
    host: bdjuno_db
    port: 5432
    user: bdjuno
    password: supersecure
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
logging:
    level: debug
    format: text
